### PR TITLE
Feature/development environment

### PR DESCRIPTION
**Pull request by Rojo**
Includes the necessary files to set up a virtual development environment with Vagrant and Virtualbox.

### CODE REVIEW

**Comment by Lyla-Fischer** [comment]
The only comment that I have is that the output of run_atlas directs the user to 0.0.0.0:8000, when 0.0.0.0 isn't in ALLOWED_HOSTS. It might be nice to add that, just so that people reading the output or who want to click on that link in the terminal can do that without having an error.

**Review by Lyla-Fischer — APPROVED** [review]

**Comment by Lyla-Fischer** [comment]
It might also be nice to add some prepopulation to the data fields. That was what I was trying to do when I got interrupted last time, because the export isn't working. However, you should be able to import from ananse_scrapers at last a subset of the data so that developers have something to work with.

**Comment by Rojo** [comment]
@maylanvn Can you work on what Lyla comments so we can merge this?

I think that adding the address to `ALLOWED_HOSTS` would require little changes.

I don't know about getting the data from `ananse_scrapers`, though. Can you check it and inform if you find it feasible for this PR?

**Comment by maylanvn** [comment]
@Lyla-Fischer  I don't know neither about getting data from  ananse_scrapers or where to search for.

**Comment by Lyla-Fischer** [comment]
I'm gonna merge this pull request, and just request the default data come in a future pull request.

**Pull request merged**
