### PR TITLE
The Logo has been Changed - Issue #76 Fix

### PR DESCRIPTION
**Pull request by steevjames**
Issue #76 has been fixed.
Logo text has been changed to 'Innovation Atlas'

### CODE REVIEW

**Comment by Lyla-Fischer** [comment]
Can you put this in a new file with a more appropriate name (like "atlas_logo" or something), and then replace the references. It will just be less confusing in the future, when we remember back in the day when Ananse was a thing (which seems to be the current trend)

**Comment by Lyla-Fischer** [comment]
Also, we have to stick with "Atlas of Innovation". Innovation Atlas is a separate thing in Canada. It might be a generic enough name that we could get away with it legally, but it would be nice to have separate search terms.

That might mean that we need more than a slap-dash fix on the logo. @annawb do we have a vector file for them to play with, so that they can reverse the order of the boxes a bit more easily, to put the larger box on the bottom?

**Comment by annawb** [comment]
Unfortunately I don’t, but I emailed high-res files to Lyla and Caro. Let me know if you need the original vectors and I can ask our designer...

**Comment by steevjames** [comment]
> Can you put this in a new file with a more appropriate name (like "atlas_logo" or something), and then replace the references. It will just be less confusing in the future, when we remember back in the day when Ananse was a thing (which seems to be the current trend)

Yes.. Will make the new one a separate logo and references to it. Also would adding 'of' in the middle and interchanging 'atlas' and 'innovation' solve the problem ?

**Comment by Lyla-Fischer** [comment]
I think so, yes. Thanks!

**Comment by steevjames** [comment]
Changes Made

**Comment by Lyla-Fischer** [comment]
Can you squash your commits? I like the philosophy of git hygene that says each commit should be an idea that is worth looking back on, when trying to figure out the history of a project. Part of that philosophy is that we edit history in order to get rid of mistakes that are found in review.

**Comment by Lyla-Fischer** [comment]
Also, I was wondering if you could change the logo so that the bigger box is on the bottom. That might mean redoing a lot of the logo, because that would mean exposing parts of the lines that the boxes are covering up, and those lines don't exist in the png version of the logo. I know that it is a lot of work, but having a nice, clean, professional looking logo would be really nice.

**Comment by Lyla-Fischer** [comment]
Oh, and sorry about complaining about the git history. You already did that. github just doesn't update it's conversation git history without a refresh, and I failed to refresh.

**Comment by steevjames** [comment]
Doing so requires recreation of the whole logo and it would be difficult. If the original vectors are provided, it can be done.
I also think that this version of logo doesn't have much of a problem, so it can be adopted. Imagining an interchanged logo doesn't look as good.

**Comment by Lyla-Fischer** [comment]
github won't let me attach the .eps file type. Can I send it to your email?

**Comment by steevjames** [comment]
Okay...

**Comment by Lyla-Fischer** [comment]
I don't have your email address. Can you look at my profile and send an email to my email address? (I don't want to put my email address in the comments here, because that means that I can never make it private again.)

**Comment by steevjames** [comment]
Yeah, I did sent an email..... (my email too was available on my profile)
 :)

**Comment by Lyla-Fischer** [comment]
Ah, sorry. I fail at using github.

**Comment by steevjames** [comment]
Made logo with 'atlas of innovation' and interchanged location of the two boxes.

**Comment by annawb** [comment]
Thank you! Actually, I feel this would look better if all the text is together in one black box, like the MESO example. What do y'all think?

**Comment by steevjames** [comment]
I too Feel the same...

**Comment by steevjames** [comment]
Would this be a better logo ?
https://pasteboard.co/HFNJGLg.png

**Comment by annawb** [comment]
That looks great, thanks!

I’d like to run it by our original logo designer though, since she might have opinions. Let’s use yours for now, and maybe change it if the designer comes up with a new one?

Thanks,
Anna

**Pull request merged**
