### PR TITLE
Add front-end design to the space profile page.

### PR DESCRIPTION
**Pull request by daggithub**
Integrated materialized framework for the front-end design of the space profile page.

### CODE REVIEW

**Comment by Lyla-Fischer** [comment]
This looks really good when a space has most of the information, but it looks a bit like there were programming errors if (in the common case) we don't have all of the information. Any chance you can make certain fields just disappear if they don't have any information to display?

**Comment by daggithub** [comment]
That's odd, I used the conditionals that where already implemented to show and hide fields... I'll test a the profile with missing fields to see what's happening.

**Comment by Lyla-Fischer** [comment]
I think that the fields themselves are hidden appropriately, but the outlines of the fields are still there, even if they don't contain anything. For example, there is an "additional information" box, even if there is no additional information.

**Comment by daggithub** [comment]
oh! I see, ok, no problem.

**Comment by ParthenonTech** [comment]
code lgtm.  wanna see it in action!

**Pull request merged**
